# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PicUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 822)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Image = QtWidgets.QLabel(self.centralwidget)
        self.label_Image.setGeometry(QtCore.QRect(60, 50, 961, 551))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_Image.setFont(font)
        self.label_Image.setAutoFillBackground(True)
        self.label_Image.setObjectName("label_Image")
        self.pushButton_Open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Open.setGeometry(QtCore.QRect(180, 680, 101, 41))
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.pushButton_Before = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Before.setGeometry(QtCore.QRect(330, 680, 101, 41))
        self.pushButton_Before.setObjectName("pushButton_Before")
        self.pushButton_Next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Next.setGeometry(QtCore.QRect(480, 680, 101, 41))
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.pushButton_Bigger = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bigger.setGeometry(QtCore.QRect(630, 680, 101, 41))
        self.pushButton_Bigger.setObjectName("pushButton_Bigger")
        self.pushButton_Smaller = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Smaller.setGeometry(QtCore.QRect(790, 680, 101, 41))
        self.pushButton_Smaller.setObjectName("pushButton_Smaller")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 绑定按钮：把按钮跟函数绑定到一起，点击一次按钮执行一次函数
        self.pushButton_Open.clicked.connect(self.Open)
        # 上一张按钮
        self.pushButton_Before.clicked.connect(self.Before)
        # 下一张按钮
        self.pushButton_Next.clicked.connect(self.Next)
        # 放大按钮
        self.pushButton_Bigger.clicked.connect(self.Bigger)
        # 缩小按钮
        self.pushButton_Smaller.clicked.connect(self.Smaller)

        # 定义列表，存储打开的图片目录下的所有图片路径
        self.picturePaths = []
        # 定义变量，存储当前打开的图片索引
        self.currentPictureIndex = 0

        # 设置label的填充模式
        self.label_Image.setScaledContents(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片预览工具"))
        self.label_Image.setText(_translate("MainWindow", "请打开目录后选择图片文件夹"))
        self.pushButton_Open.setText(_translate("MainWindow", "打开目录"))
        self.pushButton_Before.setText(_translate("MainWindow", "上一张"))
        self.pushButton_Next.setText(_translate("MainWindow", "下一张"))
        self.pushButton_Bigger.setText(_translate("MainWindow", "放大"))
        self.pushButton_Smaller.setText(_translate("MainWindow", "缩小"))

    def Open(self):
        # 1.打开一个选择目录的窗口
        path = QtWidgets.QFileDialog.getExistingDirectory(None, "请选择图片目录", os.getcwd())
        # 选择的路径不为空
        if path == '':
            return
        # 2.获取选择的图片目录下的所有图片的路径
        # （1）通过os.listdir函数来获得指定目录内的所有文件名称，在这里就是图片名称
        names = os.listdir(path)
        # (2) 把图片目录的路径 与 图片名称拼接到一起，获得图片路径
        for name in names:
            picturePath = os.path.join(path, name)
            # (3)存储而来的图片路径
            self.picturePaths.append(picturePath)
        # 3.来显示第一张图片
        # （1）判断选择的目录下是否有文件，无则返回
        if len(self.picturePaths) == 0:
            return
        # (2) 获取第一张图片的路径
        firstPicturePath = self.picturePaths[0]
        # (3)创建第一张图片的图片对象
        firstPicture = QtGui.QPixmap(firstPicturePath)
        # (4)在label上显示第一张图片
        self.label_Image.setPixmap(firstPicture)


    def Before(self):
        print('上一张')
        # 1.判断当前的图片索引是否为0，是则无法进行上一张操作
        if self.currentPictureIndex == 0:
            print('当前为第一张照片')
            return
        # 2.把当前图片索引减一
        self.currentPictureIndex -= 1
        # 3.显示上一张图片
        # （1）获取上一张图片的索引
        picturePath = self.picturePaths[self.currentPictureIndex]
        # (2)创建上一张图片
        picture = QtGui.QPixmap(picturePath)
        # (3)显示上一张图片
        self.label_Image.setPixmap(picture)

    def Next(self):
        print('下一张')
        # 1.判断当前的图片索引是否为最后一张，是则无法进行下一张操作
        if self.currentPictureIndex == len(self.picturePaths) - 1:
            print('当前为最后一张照片')
            return
        # 2.把当前图片索引加一
        self.currentPictureIndex += 1
        # 3.显示下一张图片
        # （1）获取下一张图片的所索引
        picturePath = self.picturePaths[self.currentPictureIndex]
        # (2)创建下一张图片
        picture = QtGui.QPixmap(picturePath)
        # (3)显示下一张图片
        self.label_Image.setPixmap(picture)

    def Bigger(self):
        print('放大')
        # 1.判断图片是否存在
        if len(self.picturePaths) == 0:
            return
        # 2.限高：最大尺寸
        if self.label_Image.height() > 600:
            return
        self.label_Image.setFixedSize(int(self.label_Image.width()*1.1),int(self.label_Image.height()*1.1))

    def Smaller(self):
        print('缩小')
        # 1.判断图片是否存在
        if len(self.picturePaths) == 0:
            return
        # 2.限高：最小尺寸
        if self.label_Image.height() < 100:
            return
        self.label_Image.setFixedSize(int(self.label_Image.width() * 0.9), int(self.label_Image.height() * 0.9))
        # question：图片未填充->设置label填充

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
    # 北京 有能力