# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PicZuFanf.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
import os
import requests
from lxml import etree


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Before = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Before.setGeometry(QtCore.QRect(230, 650, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_Before.setFont(font)
        self.pushButton_Before.setObjectName("pushButton_Before")
        self.pushButton_Next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Next.setGeometry(QtCore.QRect(590, 650, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_Next.setFont(font)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(70, 60, 861, 251))
        self.listWidget.setObjectName("listWidget")
        self.House1_Image = QtWidgets.QLabel(self.centralwidget)
        self.House1_Image.setGeometry(QtCore.QRect(90, 100, 151, 181))
        self.House1_Image.setAutoFillBackground(True)
        self.House1_Image.setObjectName("House1_Image")
        self.House1_Title = QtWidgets.QLabel(self.centralwidget)
        self.House1_Title.setGeometry(QtCore.QRect(260, 110, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.House1_Title.setFont(font)
        self.House1_Title.setObjectName("House1_Title")
        self.House1_Info = QtWidgets.QLabel(self.centralwidget)
        self.House1_Info.setGeometry(QtCore.QRect(260, 150, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.House1_Info.setFont(font)
        self.House1_Info.setObjectName("House1_Info")
        self.House1_From = QtWidgets.QLabel(self.centralwidget)
        self.House1_From.setGeometry(QtCore.QRect(260, 230, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.House1_From.setFont(font)
        self.House1_From.setObjectName("House1_From")
        self.House1_Price = QtWidgets.QLabel(self.centralwidget)
        self.House1_Price.setGeometry(QtCore.QRect(740, 100, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.House1_Price.setFont(font)
        # 设置颜色
        self.House1_Price.setStyleSheet("color: rgb(255,0,0,255);")
        self.House1_Price.setObjectName("House1_Price")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(70, 330, 861, 251))
        self.listWidget_2.setObjectName("listWidget_2")
        self.House2_Price = QtWidgets.QLabel(self.centralwidget)
        self.House2_Price.setGeometry(QtCore.QRect(750, 360, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.House2_Price.setFont(font)
        # 设置颜色
        self.House2_Price.setStyleSheet("color: rgb(255,0,0,255);")
        self.House2_Price.setObjectName("House2_Price")
        self.House2_Image = QtWidgets.QLabel(self.centralwidget)
        self.House2_Image.setGeometry(QtCore.QRect(90, 360, 151, 181))
        self.House2_Image.setAutoFillBackground(True)
        self.House2_Image.setObjectName("House2_Image")
        self.House2_Info = QtWidgets.QLabel(self.centralwidget)
        self.House2_Info.setGeometry(QtCore.QRect(260, 410, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.House2_Info.setFont(font)
        self.House2_Info.setObjectName("House2_Info")
        self.House2_Title = QtWidgets.QLabel(self.centralwidget)
        self.House2_Title.setGeometry(QtCore.QRect(260, 360, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.House2_Title.setFont(font)
        self.House2_Title.setObjectName("House2_Title")
        self.House2_From = QtWidgets.QLabel(self.centralwidget)
        self.House2_From.setGeometry(QtCore.QRect(260, 500, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.House2_From.setFont(font)
        self.House2_From.setObjectName("House2_From")
        self.Page = QtWidgets.QLabel(self.centralwidget)
        self.Page.setGeometry(QtCore.QRect(440, 600, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.Page.setFont(font)
        self.Page.setObjectName("Page")
        self.comboBox_Adr = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Adr.setGeometry(QtCore.QRect(840, 10, 111, 41))
        self.comboBox_Adr.setObjectName("comboBox_Adr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 设置label的填充模式：图片完全填充
        self.House1_Image.setScaledContents(True)
        self.House2_Image.setScaledContents(True)

        # 下拉框，选择城市
        self.comboBox_Adr.addItems(['北京', '上海', '深圳', '杭州'])
        # 默认北京：用于后续的网址拼接
        self.default_adr = 'bj'

        # 按钮绑定监听事件
        # 上一页
        self.pushButton_Before.clicked.connect(self.Before)
        # 下一页
        self.pushButton_Next.clicked.connect(self.Next)
        # 下拉框：int传索引， str传内容，自动传到AdrChange函数的参数i
        self.comboBox_Adr.currentIndexChanged[int].connect(self.AdrChange)
        # 房屋信息
        self.currentIndex = 0
        self.House_AllInfo = []

        # 默认北京
        self.url = 'https://' + self.default_adr + '.lianjia.com/zufang/'
        # 图片保存路径
        self.folder_name = './Image/' + self.default_adr

        # 初始化
        self.Init()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "租房查询"))
        self.pushButton_Before.setText(_translate("MainWindow", "上一页"))
        self.pushButton_Next.setText(_translate("MainWindow", "下一页"))
        self.House1_Image.setText(_translate("MainWindow", "TextLabel"))
        self.House1_Title.setText(_translate("MainWindow", "TextLabel"))
        self.House1_Info.setText(_translate("MainWindow", "TextLabel"))
        self.House1_From.setText(_translate("MainWindow", "TextLabel"))
        self.House1_Price.setText(_translate("MainWindow", "TextLabel"))
        self.House2_Price.setText(_translate("MainWindow", "TextLabel"))
        self.House2_Image.setText(_translate("MainWindow", "TextLabel"))
        self.House2_Info.setText(_translate("MainWindow", "TextLabel"))
        self.House2_Title.setText(_translate("MainWindow", "TextLabel"))
        self.House2_From.setText(_translate("MainWindow", "TextLabel"))
        self.Page.setText(_translate("MainWindow", "TextLabel"))

        # 下拉框按钮绑定事件

    def AdrChange(self, i):
        # i为索引
        print(i)
        if i == 0:
            self.default_adr = 'bj'
        elif i == 1:
            self.default_adr = 'sh'
        elif i == 2:
            self.default_adr = 'sz'
        elif i == 3:
            self.default_adr = 'hz'

        # 重新拼接获取网站链接与图片保存路径
        self.url = 'https://' + self.default_adr + '.lianjia.com/zufang/'
        self.folder_name = './Image/' + self.default_adr
        # 重新初始化
        self.Init()

        # 利用爬虫技术爬取租房信息

    def GetHouse(self):
        print(f'爬取租房信息:{self.url}')

        headers = {
            'Cookie': 'select_city=110000; lianjia_ssid=93bd2c99-b658-41a0-8dbb-a136918b9535; lianjia_uuid=01a5576f-7b7a-440b-b1b1-a881ccecafe0; srcid=eyJ0Ijoie1wiZGF0YVwiOlwiNzJiYzRjOWJhNzI4ZmJkYzM0ZWQyNWM1OWNmMzk5Mjg5YTBkMjk3OTRmYWExZjE0MDQwZTBiYjU4ODQyOTJiZTA4OWI1NjE1OTRlYjBmOTViMGE2MzM1MmE0N2JkMDIyMmU4OWYxNmVmOTAzNGQ1MTU0NjUyM2JmNDVhMzgzZTQ3ZDVhZGJlYjhhZThjOTkwNTZlNTg4ZjU3Y2Y3NzAxNzQ3ZjExYTQzZGJhMjM3NDc0NWNiMTBhOTYyNjdlMjE4ZDA0YWMzMzc3ZmJlNTMwMTU0NjFkNzI3ZjAzOGY3YTJiNjg5YWZhM2FjMmFkOGVlZTQwMTc3Y2EwNGNkMzcwZFwiLFwia2V5X2lkXCI6XCIxXCIsXCJzaWduXCI6XCI4YmFkMGMxNlwifSIsInIiOiJodHRwczovL2JqLmxpYW5qaWEuY29tL3p1ZmFuZy8iLCJvcyI6IndlYiIsInYiOiIwLjEifQ==',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
        }

        resp = requests.get(self.url, headers=headers)
        data = etree.HTML(resp.text)

        # 0 租房名称
        result0 = data.xpath('//*[@class="content__list--item--aside"]/img/@alt')
        result0_final = new_size = [j.strip() for j in result0 if j.strip() != '']
        print(len(result0_final))

        # 1 img 图片链接
        # 选择器
        result1 = data.xpath('//*[@class="content__list--item--aside"]/img/@data-src')
        print(len(result1))

        # 2 租房信息
        result2 = data.xpath('//*[@class="content__list--item--des"]')
        result2_final = []
        for i in result2:
            # 该标签下所有的字符串
            r = i.xpath('string(.)')
            new_size = [j.strip() for j in r if j.strip() != '']
            result2_final.append(''.join(new_size))
        print(len(result2_final))

        # 3 月租
        result3 = data.xpath('//*[@class="content__list--item-price"]')
        result3_final = []
        for i in result3:
            price = i.xpath('string(.)')
            new_size = [j.strip() for j in price if j.strip() != '']
            result3_final.append(''.join(new_size))
        print(len(result3_final))

        # 4 来源
        # 类选择器
        result4 = data.xpath('//*[@class="content__list--item--brand oneline"]')
        result4_final = []
        for i in result4:
            label1 = i.xpath('./span[1]/text()')
            label2 = i.xpath('./span[2]/text()')
            if len(label2) == 0:
                result4_final.append(label1[0].strip())
                continue
            result4_final.append(label1[0].strip() + ' ' + label2[0].strip())
        print(len(result4_final))

        # 每次重新选择城市时需置空，因为后续加载信息为索引0开始
        self.House_AllInfo = []

        for i in range(30):
            # print(f'租房：{i + 1}')
            # print(f'租房名称：{result0[i]}')
            # print(f'实物图片：{result1[i]}')
            # print(f'租房信息：{result2_final[i]}')
            # print(f'月租：{result3_final[i]}')
            # print(f'租房来源：{result4_final[i]}')
            # print()

            # 由字典形式保存至列表中
            house_dic = {'租房': i + 1, 'title': result0[i], 'image': result1[i], 'info': result2_final[i]
                , 'price': result3_final[i], 'from': result4_final[i]}
            self.House_AllInfo.append(house_dic)

    # 通过爬取所得的图片链接下载图片
    def DownloadImage(self):
        print('下载图片')

        if not os.path.exists(self.folder_name):
            os.mkdir(self.folder_name)

        for i in range(len(self.House_AllInfo)):
            image_url = self.House_AllInfo[i]['image']
            save_path = self.folder_name + '/' + str(i) + '.jpg'
            # 判断该图片是否已存在，不存在则写入文件夹中
            if not os.path.exists(save_path):
                response = requests.get(image_url)
                with open(save_path, "wb") as file:
                    file.write(response.content)

    # 初始化
    def Init(self):
        print('初始化')
        self.currentIndex = 0

        # 获取租房信息：租房名称，图片链接，价格，详情，来源，并将信息储存至self.
        self.GetHouse()
        # 下载图片
        self.DownloadImage()

        # 该页第一间租房
        # 租房名称
        self.House1_Title.setText(self.House_AllInfo[2 * self.currentIndex]['title'])
        # 图片显示
        # (1) 获取图片
        firstPicturePath = self.folder_name + '/' + str(2 * self.currentIndex) + '.jpg'
        # (2)创建图片的图片对象
        firstPicture = QtGui.QPixmap(firstPicturePath)
        # (3)在label上显示图片
        self.House1_Image.setPixmap(firstPicture)
        # 租房信息
        self.House1_Info.setText(self.House_AllInfo[2 * self.currentIndex]['info'])
        # 月租
        self.House1_Price.setText(self.House_AllInfo[2 * self.currentIndex]['price'])
        # 来源
        self.House1_From.setText(self.House_AllInfo[2 * self.currentIndex]['from'])

        # 该页第二间租房
        self.House2_Title.setText(self.House_AllInfo[2 * self.currentIndex + 1]['title'])
        # 图片显示
        # (1) 获取第一张图片
        firstPicturePath = self.folder_name + '/' + str(2 * self.currentIndex + 1) + '.jpg'
        # (2)创建第一张图片的图片对象
        firstPicture = QtGui.QPixmap(firstPicturePath)
        # (3)在label上显示第一张图片
        self.House2_Image.setPixmap(firstPicture)
        self.House2_Info.setText(self.House_AllInfo[2 * self.currentIndex + 1]['info'])
        self.House2_Price.setText(self.House_AllInfo[2 * self.currentIndex + 1]['price'])
        self.House2_From.setText(self.House_AllInfo[2 * self.currentIndex + 1]['from'])

        # 页数
        self.Page.setText(f'{self.currentIndex + 1}/{int(len(self.House_AllInfo) // 2)}')

    def Before(self):
        print('上一页')
        if self.currentIndex == 0:
            print('当前为第一页')
            return
        # 每页显示两页
        self.currentIndex -= 1
        # 获取上一页信息
        # 该页第一间租房
        self.House1_Title.setText(self.House_AllInfo[2 * self.currentIndex]['title'])

        # (2) 获取第一张图片
        firstPicturePath = self.folder_name + '/' + str(2 * self.currentIndex) + '.jpg'
        # (3)创建第一张图片的图片对象
        firstPicture = QtGui.QPixmap(firstPicturePath)
        # (4)在label上显示第一张图片
        self.House1_Image.setPixmap(firstPicture)

        self.House1_Info.setText(self.House_AllInfo[2 * self.currentIndex]['info'])
        self.House1_Price.setText(self.House_AllInfo[2 * self.currentIndex]['price'])
        self.House1_From.setText(self.House_AllInfo[2 * self.currentIndex]['from'])

        # 该页第二
        self.House2_Title.setText(self.House_AllInfo[2 * self.currentIndex + 1]['title'])
        # (2) 获取第一张图片
        firstPicturePath = self.folder_name + '/' + str(2 * self.currentIndex + 1) + '.jpg'
        # (3)创建第一张图片的图片对象
        firstPicture = QtGui.QPixmap(firstPicturePath)
        # (4)在label上显示第一张图片
        self.House2_Image.setPixmap(firstPicture)

        self.House2_Info.setText(self.House_AllInfo[2 * self.currentIndex + 1]['info'])
        self.House2_Price.setText(self.House_AllInfo[2 * self.currentIndex + 1]['price'])
        self.House2_From.setText(self.House_AllInfo[2 * self.currentIndex + 1]['from'])

        # 页数
        self.Page.setText(f'{self.currentIndex + 1}/{int(len(self.House_AllInfo) // 2)}')

    def Next(self):
        print('下一页')
        # 偶数页
        if 2*(self.currentIndex+1) >= int(len(self.House_AllInfo)) or 2*(self.currentIndex+1) >= int(len(self.House_AllInfo)):
            print('当前为最后一页')
            return
        self.currentIndex += 1
        # 获取下一页信息
        # 该页第一间租房
        self.House1_Title.setText(self.House_AllInfo[2 * self.currentIndex]['title'])

        # (2) 获取第一张图片
        firstPicturePath = self.folder_name + '/' + str(2 * self.currentIndex) + '.jpg'
        # (3)创建第一张图片的图片对象
        firstPicture = QtGui.QPixmap(firstPicturePath)
        # (4)在label上显示第一张图片
        self.House1_Image.setPixmap(firstPicture)

        self.House1_Info.setText(self.House_AllInfo[2 * self.currentIndex]['info'])
        self.House1_Price.setText(self.House_AllInfo[2 * self.currentIndex]['price'])
        self.House1_From.setText(self.House_AllInfo[2 * self.currentIndex]['from'])

        # 该页第二
        self.House2_Title.setText(self.House_AllInfo[2 * self.currentIndex + 1]['title'])
        # (2) 获取第一张图片
        firstPicturePath = self.folder_name + '/' + str(2 * self.currentIndex + 1) + '.jpg'
        # (3)创建第一张图片的图片对象
        firstPicture = QtGui.QPixmap(firstPicturePath)
        # (4)在label上显示第一张图片
        self.House2_Image.setPixmap(firstPicture)

        self.House2_Info.setText(self.House_AllInfo[2 * self.currentIndex + 1]['info'])
        self.House2_Price.setText(self.House_AllInfo[2 * self.currentIndex + 1]['price'])
        self.House2_From.setText(self.House_AllInfo[2 * self.currentIndex + 1]['from'])

        # 页数
        self.Page.setText(f'{self.currentIndex + 1}/{int(len(self.House_AllInfo) // 2)}')

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
    # 北京 有能力

