# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(909, 712)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Open.setGeometry(QtCore.QRect(60, 570, 93, 28))
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.pushButton_Before = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Before.setGeometry(QtCore.QRect(180, 570, 93, 28))
        self.pushButton_Before.setObjectName("pushButton_Before")
        self.pushButton_Next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Next.setGeometry(QtCore.QRect(310, 570, 93, 28))
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.pushButton_Bigger = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bigger.setGeometry(QtCore.QRect(440, 570, 93, 28))
        self.pushButton_Bigger.setObjectName("pushButton_Bigger")
        self.label_Image = QtWidgets.QLabel(self.centralwidget)
        self.label_Image.setGeometry(QtCore.QRect(20, 0, 791, 521))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Image.setFont(font)
        self.label_Image.setAutoFillBackground(True)
        self.label_Image.setObjectName("label_Image")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(570, 570, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片浏览工具"))
        self.pushButton_Open.setText(_translate("MainWindow", "打开目录"))
        self.pushButton_Before.setText(_translate("MainWindow", "上一张"))
        self.pushButton_Next.setText(_translate("MainWindow", "下一张"))
        self.pushButton_Bigger.setText(_translate("MainWindow", "放大"))
        self.label_Image.setText(_translate("MainWindow", "请打开目录后选择图片文件夹"))
        self.pushButton_5.setText(_translate("MainWindow", "缩小"))
